library(tidyverse)
library(rvest)
library(jsonlite)
library(janitor)

source("seasons.R")
source("teams.R")
source("players.R")
source("games.R")
source("awards.R")
source("utility.R")

seasons_table <- get_season_df()
teams_table <- get_team_df()
players_table <- get_player_df()
colleges_table <- get_college_df(players_table)
games_table <- get_game_df()
awards_table <- get_awards_df()
