library(tidyverse)
library(rvest)
library(jsonlite)
library(janitor)
library(polite)
library(memoise)

source("seasons.R")
source("teams.R")
source("players.R")
source("games.R")
source("awards.R")
source("utility.R")

seasons_table <- m_get_season_df()
teams_table <- m_get_team_df()
players_table <- m_get_player_df()
colleges_table <- m_get_college_df(m_get_player_df())
games_table <- m_get_game_df()
awards_table <- m_get_awards_df()
